### ISSUE TITLE
Broken links in page https://github.com/RevolutionAnalytics/checkpoint-server/blob/master/docs/MRAN-server-overview.md

### ISSUE THREAD

**Issue by molecules** [RevolutionAnalytics/checkpoint-server#20]
The following links (found at https://github.com/RevolutionAnalytics/checkpoint-server/blob/master/docs/MRAN-server-overview.md) are broken:
    http://revolutionanalytics.github.io/RRT
    http://mran.revolutionanalytics.com/metadata/
    http://mran.revolutionanalytics.com/snapshots/

**Comment by cmosetick** [comment]
Hi @molecules, thank you for your report. That page is very out of date. I'll update the documentation and check all the links.

**Comment by molecules** [comment]
No broken links at the moment. Thanks!
